In [ ]:
import pandas as pd
import tqdm, os
import pickle
import warnings
warnings.simplefilter("ignore")

import sys
sys.path.insert(0, "../..")

from utils.acoustics_processing import get_mfccs
from utils.articulation_processing import get_aemri_articulatory_features

In [2]:
df = pd.read_csv("../data_processing/dataset_construction/datasets/processed_aemri.csv")
df["subject"] = df["art_f"].apply(lambda x: os.path.basename(x).split("_")[2])

In [3]:
df

,phone1_start,phone1_end,phone2_start,phone2_end,phone1,phone2,context,word,word_id,art_f,ac_f,subject
0,2.28270,2.33270,2.33270,2.43270,h,ɝ,h,her,0.0,/Volumes/Transcend/USC-TIMIT/MRI/Data/M1/avi/u...,/Volumes/Transcend/USC-TIMIT/MRI/Data/M1/wav/u...,m1
1,2.43270,2.64270,2.64270,2.67270,ɔ,b,ɔ,auburn,1.0,/Volumes/Transcend/USC-TIMIT/MRI/Data/M1/avi/u...,/Volumes/Transcend/USC-TIMIT/MRI/Data/M1/wav/u...,m1
2,2.64270,2.67270,2.67270,2.82270,b,ɝ,ɔ_b,auburn,1.0,/Volumes/Transcend/USC-TIMIT/MRI/Data/M1/avi/u...,/Volumes/Transcend/USC-TIMIT/MRI/Data/M1/wav/u...,m1
3,2.67270,2.82270,2.82270,2.86270,ɝ,n,ɔ_b_ɝ,auburn,1.0,/Volumes/Transcend/USC-TIMIT/MRI/Data/M1/avi/u...,/Volumes/Transcend/USC-TIMIT/MRI/Data/M1/wav/u...,m1
4,2.86270,2.96270,2.96270,3.19270,h,ɛ,h,hair,2.0,/Volumes/Transcend/USC-TIMIT/MRI/Data/M1/avi/u...,/Volumes/Transcend/USC-TIMIT/MRI/Data/M1/wav/u...,m1
...,...,...,...,...,...,...,...,...,...,...,...,...
98930,22.56169,22.59172,22.59172,22.63176,m,u,m,MOVIES,36.0,/Volumes/Transcend/USC-TIMIT/MRI/Data/F1/avi/u...,/Volumes/Transcend/USC-TIMIT/MRI/Data/F1/wav/u...,f1
98931,22.59172,22.63176,22.63176,22.68181,u,v,m_u,MOVIES,36.0,/Volumes/Transcend/USC-TIMIT/MRI/Data/F1/avi/u...,/Volumes/Transcend/USC-TIMIT/MRI/Data/F1/wav/u...,f1
98932,22.63176,22.68181,22.68181,22.88201,v,i,m_u_v,MOVIES,36.0,/Volumes/Transcend/USC-TIMIT/MRI/Data/F1/avi/u...,/Volumes/Transcend/USC-TIMIT/MRI/Data/F1/wav/u...,f1
98933,22.68181,22.88201,22.88201,23.12225,i,z,m_u_v_i,MOVIES,36.0,/Volumes/Transcend/USC-TIMIT/MRI/Data/F1/avi/u...,/Volumes/Transcend/USC-TIMIT/MRI/Data/F1/wav/u...,f1
98934,23.12225,23.15228,23.15228,23.18231,ð,ʌ,ð,THE,37.0,/Volumes/Transcend/USC-TIMIT/MRI/Data/F1/avi/u...,/Volumes/Transcend/USC-TIMIT/MRI/Data/F1/wav/u...,f1

In [ ]:
tokens = {
    "start": [],
    "end": [],
    "syllable": [],
    "art_f": [],
    "ac_f": [],
    "subject": [],
}

metadata = set(
    [(start, end, target, art_f, ac_f, subject) for start, end, target, art_f, ac_f, subject in zip(df["syllable1_start"], df["syllable1_end"], df["syllable1"], df["art_f"], df["ac_f"], df["subject"])] + 
    [(start, end, target, art_f, ac_f, subject) for start, end, target, art_f, ac_f, subject in zip(df["syllable2_start"], df["syllable2_end"], df["syllable2"], df["art_f"], df["ac_f"], df["subject"])]
)

metadata = sorted(list(metadata), key=lambda x: (x[3], x[4], x[5]))

for start, end, target, art_f, ac_f, subject in metadata:
    tokens["start"].append(start)
    tokens["end"].append(end)
    tokens["syllable"].append(target)
    tokens["art_f"].append(art_f)
    tokens["ac_f"].append(ac_f)
    tokens["subject"].append(subject)

In [5]:
token_df = pd.DataFrame(tokens)

In [6]:
token_df

,start,end,phone,art_f,ac_f,subject
0,2.28270,2.33270,h,/Volumes/Transcend/USC-TIMIT/MRI/Data/M1/avi/u...,/Volumes/Transcend/USC-TIMIT/MRI/Data/M1/wav/u...,m1
1,2.43270,2.64270,ɔ,/Volumes/Transcend/USC-TIMIT/MRI/Data/M1/avi/u...,/Volumes/Transcend/USC-TIMIT/MRI/Data/M1/wav/u...,m1
2,2.64270,2.67270,b,/Volumes/Transcend/USC-TIMIT/MRI/Data/M1/avi/u...,/Volumes/Transcend/USC-TIMIT/MRI/Data/M1/wav/u...,m1
3,2.67270,2.82270,ɝ,/Volumes/Transcend/USC-TIMIT/MRI/Data/M1/avi/u...,/Volumes/Transcend/USC-TIMIT/MRI/Data/M1/wav/u...,m1
4,2.86270,2.96270,h,/Volumes/Transcend/USC-TIMIT/MRI/Data/M1/avi/u...,/Volumes/Transcend/USC-TIMIT/MRI/Data/M1/wav/u...,m1
...,...,...,...,...,...,...
129379,21.77090,21.80093,m,/Volumes/Transcend/USC-TIMIT/MRI/Data/F1/avi/u...,/Volumes/Transcend/USC-TIMIT/MRI/Data/F1/wav/u...,f1
129380,21.92105,21.95108,z,/Volumes/Transcend/USC-TIMIT/MRI/Data/F1/avi/u...,/Volumes/Transcend/USC-TIMIT/MRI/Data/F1/wav/u...,f1
129381,22.53166,22.56169,m,/Volumes/Transcend/USC-TIMIT/MRI/Data/F1/avi/u...,/Volumes/Transcend/USC-TIMIT/MRI/Data/F1/wav/u...,f1
129382,22.88201,23.12225,z,/Volumes/Transcend/USC-TIMIT/MRI/Data/F1/avi/u...,/Volumes/Transcend/USC-TIMIT/MRI/Data/F1/wav/u...,f1
129383,23.15228,23.18231,ʌ,/Volumes/Transcend/USC-TIMIT/MRI/Data/F1/avi/u...,/Volumes/Transcend/USC-TIMIT/MRI/Data/F1/wav/u...,f1

In [20]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from utils.models import VideoAutoencoder, SequenceAutoencoder

In [8]:
def latent_stats(z):
    # z: (B, latent_dim)
    return {
        "latent_var_mean": z.var(dim=0).mean().item(),
        "latent_var_min":  z.var(dim=0).min().item(),
        "latent_var_max":  z.var(dim=0).max().item(),
    }

def batch_diversity(x):
    # x: (B, ...)
    x_flat = x.reshape(x.size(0), -1)
    return x_flat.std(dim=0).mean().item()

def visualize(clean, recon, name="Reconstruction"):
    import matplotlib.pyplot as plt

    try:
        # Get both channels, frame 0 of first batch element
        clean_mri= clean[0, 0, 0].cpu().numpy()
    except RuntimeError:
        clean_mri = clean[0, 0, 0].detach().cpu().numpy()

    recon_mri = recon[0, 0, 0].detach().cpu().numpy()

    plt.figure(figsize=(10, 6))

    plt.subplot(1, 2, 1)
    plt.imshow(clean_mri, cmap='gray')
    plt.title("Original (MRI)")
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(recon_mri, cmap='gray')
    plt.title(f"{name} (MRI)")
    plt.axis('off')

    plt.tight_layout()
    plt.savefig(f"video_visualization/aemri/{name.lower()}.png", dpi=300)
    plt.close("all")

def combined_loss(y_true, y_pred, warped_x, criterion, plot=False, ratio=1):
    diff_true = y_true[:, :, 1:, :, :] - y_true[:, :, :-1, :, :]
    diff_pred = y_pred[:, :, 1:, :, :] - y_pred[:, :, :-1, :, :]
    loss = criterion(diff_true, diff_pred) * (1 - ratio) + criterion(y_true, y_pred) * ratio

    if plot:
        visualize(diff_true, diff_pred, name="Reconstruction (differential)")
        visualize(y_true, y_pred, name="Reconstruction")
        visualize(y_true, warped_x, name="Transformation")

    return loss

In [9]:
device = "mps" if torch.backends.mps.is_available() else "cpu"

BATCH_SIZE = 4

In [ ]:
log = {
    "batch_idx": [],
    "loss": [],
}

art_model = VideoAutoencoder(
    input_shape=(5, 68, 68),
    latent_dim=1024,
    use_mlp=True,
    grid_sample_cpu_fallback=True,
).to(device)

art_criterion = nn.MSELoss()
art_optimizer = torch.optim.Adam(art_model.parameters(), lr=0.001)

shuffled_token_df = token_df.sample(frac=1, random_state=42).reset_index(drop=True)

pbar = tqdm.tqdm(shuffled_token_df.iterrows(), total=len(shuffled_token_df))

art_model.train()

batch = []
batch_idx = 0
for idx, (_, data) in enumerate(pbar):

    start, end, phone, art_f, ac_f, subject = data["start"], data["end"], data["phone"], data["art_f"], data["ac_f"], data["subject"]
    
    articulatory_features = get_aemri_articulatory_features(art_f, start, end)

    if articulatory_features is None:
        continue

    batch.append(
        torch.tensor(articulatory_features, dtype=torch.float32)
    )

    # --------------------------------------------------
    # When batch is ready
    # --------------------------------------------------
    if len(batch) < BATCH_SIZE:
        continue
    batch_idx += 1

    art_batch = torch.stack(batch).to(device)  # (B,T,P,C)
    batch.clear()

    # ===== Articulatory =====
    art_out, art_warped_x, art_z = art_model(art_batch, return_warped_x=True, return_latent=True)
    art_loss = combined_loss(art_batch, art_out, art_warped_x, art_criterion, plot=batch_idx % 30 == 0, ratio=0.5)

    art_optimizer.zero_grad()
    art_loss.backward()
    art_optimizer.step()

    log["batch_idx"].append(batch_idx)
    log["loss"].append(art_loss.item())
    pbar.set_description(
        f"{batch_idx}: ART {art_loss.item():.4f}"
    )

    # --------------------------------------------------
    # Diagnostics every 1000 updates
    # --------------------------------------------------
    if (batch_idx) % 300 == 0:
        with torch.no_grad():
            art_stats = latent_stats(art_z)

        print(
            f"[ART] latent var mean={art_stats['latent_var_mean']:.4e}, "
            f"min={art_stats['latent_var_min']:.4e}"
        )

        print(
            f"[ART] input std={batch_diversity(art_batch):.4e}, "
            f"recon std={batch_diversity(art_out):.4e}"
        )

        torch.save(art_model.state_dict(), "ckpts/aemri/art_model_ckpt.pth")
        pd.DataFrame(log).to_csv("ckpts/aemri/art_model_training_log.csv", index=False)

torch.save(art_model.state_dict(), "ckpts/aemri/art_model_ckpt.pth")
pd.DataFrame(log).to_csv("ckpts/aemri/art_model_training_log.csv", index=False)

300: ART 0.3035:   1%|          | 1196/129384 [00:54<1:26:14, 24.77it/s]

[ART] latent var mean=8.1664e+03, min=9.1396e-02
[ART] input std=4.1277e-01, recon std=4.7094e-02

600: ART 0.2895:   2%|▏         | 2400/129384 [01:48<3:28:43, 10.14it/s]

[ART] latent var mean=3.2170e+04, min=2.1764e-01
[ART] input std=3.8939e-01, recon std=6.3191e-02

900: ART 0.3051:   3%|▎         | 3600/129384 [02:49<3:46:36,  9.25it/s]

[ART] latent var mean=1.8708e+04, min=1.1649e-01
[ART] input std=3.9841e-01, recon std=2.8425e-02

1200: ART 0.2956:   4%|▎         | 4800/129384 [04:10<4:16:19,  8.10it/s]

[ART] latent var mean=2.0295e+05, min=2.3269e+00
[ART] input std=4.3266e-01, recon std=8.3060e-02

1500: ART 0.3316:   5%|▍         | 6000/129384 [05:26<3:37:26,  9.46it/s]

[ART] latent var mean=3.4899e+04, min=6.4874e-01
[ART] input std=3.8962e-01, recon std=1.4526e-02

1800: ART 0.3160:   6%|▌         | 7200/129384 [06:30<3:26:45,  9.85it/s]

[ART] latent var mean=2.0374e+05, min=6.9569e-02
[ART] input std=4.0815e-01, recon std=4.0091e-02

2100: ART 0.3092:   6%|▋         | 8396/129384 [07:31<1:28:49, 22.70it/s]

[ART] latent var mean=4.2727e+05, min=7.2018e-01
[ART] input std=4.0104e-01, recon std=5.5900e-02

2400: ART 0.3102:   7%|▋         | 9596/129384 [08:29<1:25:26, 23.37it/s]

[ART] latent var mean=1.0449e+06, min=2.0218e+00
[ART] input std=3.9835e-01, recon std=5.1065e-02

2700: ART 0.3076:   8%|▊         | 10796/129384 [09:26<1:24:00, 23.53it/s]

[ART] latent var mean=1.3520e+06, min=1.7562e-01
[ART] input std=4.2636e-01, recon std=5.2827e-02

3000: ART 0.2952:   9%|▉         | 11996/129384 [10:23<1:22:29, 23.72it/s]

[ART] latent var mean=2.3787e+06, min=2.7604e+00
[ART] input std=4.0979e-01, recon std=5.3342e-02

3300: ART 0.3028:  10%|█         | 13196/129384 [11:20<1:23:49, 23.10it/s]

[ART] latent var mean=9.5001e+05, min=8.8491e+01
[ART] input std=3.7922e-01, recon std=4.6763e-02

3600: ART 0.3440:  11%|█         | 14396/129384 [12:17<1:21:20, 23.56it/s]

[ART] latent var mean=9.1272e+05, min=1.5899e+01
[ART] input std=4.1863e-01, recon std=3.6902e-02

3900: ART 0.3059:  12%|█▏        | 15596/129384 [13:14<1:20:19, 23.61it/s]

[ART] latent var mean=9.6000e+06, min=4.0321e+02
[ART] input std=3.6771e-01, recon std=4.1423e-02

4200: ART 0.2959:  13%|█▎        | 16800/129384 [14:10<3:03:43, 10.21it/s]

[ART] latent var mean=3.5600e+07, min=3.3952e+03
[ART] input std=4.3591e-01, recon std=7.2626e-02

4500: ART 0.3201:  14%|█▍        | 18000/129384 [15:05<2:56:14, 10.53it/s]

[ART] latent var mean=4.4951e+06, min=7.7598e+01
[ART] input std=3.7168e-01, recon std=3.6666e-02

4800: ART 0.3150:  15%|█▍        | 19200/129384 [15:59<2:52:00, 10.68it/s]

[ART] latent var mean=3.0121e+07, min=3.1756e+03
[ART] input std=4.4168e-01, recon std=5.6730e-02

5100: ART 0.3082:  16%|█▌        | 20400/129384 [16:54<2:54:17, 10.42it/s]

[ART] latent var mean=1.0056e+07, min=8.1899e+02
[ART] input std=3.4966e-01, recon std=5.9305e-02

5400: ART 0.3158:  17%|█▋        | 21600/129384 [17:48<2:51:59, 10.44it/s]

[ART] latent var mean=2.4965e+07, min=1.9169e+02
[ART] input std=4.3884e-01, recon std=5.6622e-02

5700: ART 0.3000:  18%|█▊        | 22800/129384 [18:43<2:52:56, 10.27it/s]

[ART] latent var mean=6.4996e+07, min=1.5563e+02
[ART] input std=3.8216e-01, recon std=4.3908e-02

6000: ART 0.2948:  19%|█▊        | 24000/129384 [19:37<2:50:01, 10.33it/s]

[ART] latent var mean=1.6107e+08, min=2.7902e+03
[ART] input std=4.1945e-01, recon std=8.3890e-02

6300: ART 0.2899:  19%|█▉        | 25196/129384 [20:34<1:12:01, 24.11it/s]

[ART] latent var mean=4.8864e+07, min=1.4743e+03
[ART] input std=3.3045e-01, recon std=8.7158e-02

6600: ART 0.3045:  20%|██        | 26396/129384 [21:29<1:10:47, 24.25it/s]

[ART] latent var mean=1.5094e+08, min=5.8083e+01
[ART] input std=4.2828e-01, recon std=6.7293e-02

6900: ART 0.2855:  21%|██▏       | 27596/129384 [22:30<1:34:10, 18.01it/s]

[ART] latent var mean=3.3120e+08, min=2.3838e+02
[ART] input std=3.7922e-01, recon std=7.3788e-02

7200: ART 0.2852:  22%|██▏       | 28796/129384 [23:45<1:37:14, 17.24it/s]

[ART] latent var mean=1.4728e+07, min=3.0907e+01
[ART] input std=2.5933e-01, recon std=1.4348e-02

7500: ART 0.2952:  23%|██▎       | 29996/129384 [25:02<1:39:49, 16.60it/s]

[ART] latent var mean=4.2307e+08, min=3.5403e+01
[ART] input std=4.2029e-01, recon std=6.9454e-02

7800: ART 0.2919:  24%|██▍       | 31196/129384 [26:20<1:40:28, 16.29it/s]

[ART] latent var mean=2.7260e+08, min=1.4037e+02
[ART] input std=3.9632e-01, recon std=5.9561e-02

8100: ART 0.2848:  25%|██▌       | 32396/129384 [27:31<1:01:22, 26.34it/s]

[ART] latent var mean=3.4132e+08, min=1.1070e+03
[ART] input std=4.1799e-01, recon std=9.2646e-02

8400: ART 0.2841:  26%|██▌       | 33596/129384 [28:23<59:28, 26.84it/s]

[ART] latent var mean=4.2602e+08, min=2.3873e+03
[ART] input std=4.2327e-01, recon std=9.3360e-02

8700: ART 0.2931:  27%|██▋       | 34800/129384 [29:14<2:19:49, 11.27it/s]

[ART] latent var mean=6.1082e+07, min=5.1345e+02
[ART] input std=4.4214e-01, recon std=5.3779e-02

9000: ART 0.3229:  28%|██▊       | 36000/129384 [30:05<2:18:00, 11.28it/s]

[ART] latent var mean=2.7650e+08, min=1.1503e+03
[ART] input std=5.0056e-01, recon std=6.1578e-02

9300: ART 0.2920:  29%|██▉       | 37200/129384 [30:55<2:16:33, 11.25it/s]

[ART] latent var mean=5.5578e+08, min=2.3812e+03
[ART] input std=4.2235e-01, recon std=9.4986e-02

9600: ART 0.2897:  30%|██▉       | 38400/129384 [31:45<2:14:47, 11.25it/s]

[ART] latent var mean=4.7334e+08, min=2.5521e+02
[ART] input std=3.9936e-01, recon std=6.9291e-02

9900: ART 0.3069:  31%|███       | 39600/129384 [32:35<2:13:50, 11.18it/s]

[ART] latent var mean=3.8831e+08, min=9.1231e+01
[ART] input std=4.2956e-01, recon std=8.4782e-02

10200: ART 0.2742:  32%|███▏      | 40800/129384 [33:25<2:13:49, 11.03it/s]

[ART] latent var mean=3.1474e+08, min=7.7624e+02
[ART] input std=3.8019e-01, recon std=5.8484e-02

10500: ART 0.3047:  32%|███▏      | 42000/129384 [34:16<2:12:53, 10.96it/s]

[ART] latent var mean=5.5383e+08, min=1.1577e+02
[ART] input std=4.1226e-01, recon std=8.7691e-02

10800: ART 0.3054:  33%|███▎      | 43200/129384 [35:09<2:20:14, 10.24it/s]

[ART] latent var mean=1.5740e+06, min=1.2890e+00
[ART] input std=3.4215e-01, recon std=8.1934e-03

11100: ART 0.2958:  34%|███▍      | 44400/129384 [36:00<2:16:59, 10.34it/s]

[ART] latent var mean=2.0112e+07, min=2.2919e+02
[ART] input std=3.9782e-01, recon std=1.7049e-02

11400: ART 0.2956:  35%|███▌      | 45600/129384 [36:53<2:05:50, 11.10it/s]

[ART] latent var mean=7.6297e+08, min=5.0406e+03
[ART] input std=4.3871e-01, recon std=7.5605e-02

11700: ART 0.2990:  36%|███▌      | 46800/129384 [37:44<2:02:04, 11.27it/s]

[ART] latent var mean=1.9840e+08, min=3.7086e+02
[ART] input std=4.4109e-01, recon std=4.5924e-02

12000: ART 0.3289:  37%|███▋      | 48000/129384 [38:35<2:03:50, 10.95it/s]

[ART] latent var mean=2.7259e+07, min=4.8872e+01
[ART] input std=4.1159e-01, recon std=1.2639e-02

12300: ART 0.3037:  38%|███▊      | 49200/129384 [39:26<2:02:15, 10.93it/s]

[ART] latent var mean=1.4467e+09, min=1.6366e+04
[ART] input std=4.3704e-01, recon std=7.5493e-02

12600: ART 0.3058:  39%|███▉      | 50400/129384 [40:17<1:59:05, 11.05it/s]

[ART] latent var mean=7.2727e+07, min=2.2243e+01
[ART] input std=3.1558e-01, recon std=2.2024e-02

12900: ART 0.3276:  40%|███▉      | 51600/129384 [41:07<1:56:00, 11.18it/s]

[ART] latent var mean=1.3406e+08, min=1.3491e+03
[ART] input std=2.9413e-01, recon std=4.4616e-02

13200: ART 0.2920:  41%|████      | 52800/129384 [41:59<1:53:45, 11.22it/s]

[ART] latent var mean=1.0117e+09, min=2.1026e+02
[ART] input std=3.9006e-01, recon std=5.8719e-02

13500: ART 0.3115:  42%|████▏     | 54000/129384 [42:49<1:53:11, 11.10it/s]

[ART] latent var mean=1.4019e+09, min=3.5123e+04
[ART] input std=4.5044e-01, recon std=7.0141e-02

13800: ART 0.3207:  43%|████▎     | 55200/129384 [43:40<1:52:18, 11.01it/s]

[ART] latent var mean=5.5995e+08, min=6.9741e+05
[ART] input std=3.9836e-01, recon std=5.1588e-02

14100: ART 0.3104:  44%|████▎     | 56400/129384 [44:31<1:47:40, 11.30it/s]

[ART] latent var mean=8.9953e+08, min=6.0485e+04
[ART] input std=4.3008e-01, recon std=6.4387e-02

14400: ART 0.3152:  45%|████▍     | 57600/129384 [45:21<1:47:08, 11.17it/s]

[ART] latent var mean=2.2344e+09, min=7.5569e+05
[ART] input std=4.6994e-01, recon std=8.9197e-02

14700: ART 0.3053:  45%|████▌     | 58800/129384 [46:12<1:43:41, 11.35it/s]

[ART] latent var mean=1.1423e+09, min=8.6459e+04
[ART] input std=4.3979e-01, recon std=4.6294e-02

15000: ART 0.2999:  46%|████▋     | 60000/129384 [47:02<1:47:18, 10.78it/s]

[ART] latent var mean=1.6200e+09, min=2.2867e+05
[ART] input std=4.4464e-01, recon std=7.9702e-02

15300: ART 0.3162:  47%|████▋     | 61200/129384 [47:53<1:42:19, 11.11it/s]

[ART] latent var mean=5.4241e+07, min=5.1209e+03
[ART] input std=4.1391e-01, recon std=2.4930e-02

15600: ART 0.3045:  48%|████▊     | 62400/129384 [48:44<1:39:02, 11.27it/s]

[ART] latent var mean=2.2183e+09, min=5.7815e+05
[ART] input std=4.2052e-01, recon std=7.3342e-02

15900: ART 0.2878:  49%|████▉     | 63600/129384 [49:35<1:43:28, 10.60it/s]

[ART] latent var mean=3.4323e+09, min=3.1906e+05
[ART] input std=3.8827e-01, recon std=8.9720e-02

16200: ART 0.3003:  50%|█████     | 64800/129384 [50:26<1:37:09, 11.08it/s]

[ART] latent var mean=1.3045e+09, min=1.0015e+05
[ART] input std=4.5017e-01, recon std=6.1586e-02

16500: ART 0.3211:  51%|█████     | 66000/129384 [51:17<1:35:09, 11.10it/s]

[ART] latent var mean=1.3040e+09, min=2.9755e+05
[ART] input std=4.8007e-01, recon std=5.6160e-02

16800: ART 0.2978:  52%|█████▏    | 67200/129384 [52:08<1:34:01, 11.02it/s]

[ART] latent var mean=2.7377e+09, min=9.5160e+04
[ART] input std=4.4000e-01, recon std=6.1412e-02

17100: ART 0.2795:  53%|█████▎    | 68400/129384 [53:00<1:33:19, 10.89it/s]

[ART] latent var mean=3.5453e+09, min=9.7144e+04
[ART] input std=3.8091e-01, recon std=7.5818e-02

17400: ART 0.3123:  54%|█████▍    | 69600/129384 [53:50<1:29:52, 11.09it/s]

[ART] latent var mean=1.7181e+09, min=1.6327e+05
[ART] input std=4.0905e-01, recon std=6.3076e-02

17700: ART 0.3506:  55%|█████▍    | 70800/129384 [54:41<1:29:20, 10.93it/s]

[ART] latent var mean=1.6003e+08, min=3.4204e+04
[ART] input std=3.3861e-01, recon std=5.3284e-02

18000: ART 0.2810:  56%|█████▌    | 72000/129384 [55:32<1:26:36, 11.04it/s]

[ART] latent var mean=6.6343e+09, min=4.9691e+05
[ART] input std=4.1413e-01, recon std=8.9948e-02

18300: ART 0.3070:  57%|█████▋    | 73200/129384 [56:23<1:23:21, 11.23it/s]

[ART] latent var mean=6.2447e+08, min=2.0415e+04
[ART] input std=4.0976e-01, recon std=5.3462e-02

18600: ART 0.2948:  58%|█████▊    | 74400/129384 [57:14<1:21:44, 11.21it/s]

[ART] latent var mean=7.6764e+09, min=1.2133e+04
[ART] input std=3.9036e-01, recon std=7.3360e-02

18900: ART 0.3028:  58%|█████▊    | 75600/129384 [58:06<1:21:06, 11.05it/s]

[ART] latent var mean=2.4754e+08, min=5.3493e+04
[ART] input std=3.6854e-01, recon std=4.5265e-02

19200: ART 0.2956:  59%|█████▉    | 76800/129384 [58:57<1:21:32, 10.75it/s]

[ART] latent var mean=3.5747e+09, min=7.3250e+04
[ART] input std=4.4649e-01, recon std=8.5403e-02

19500: ART 0.3051:  60%|██████    | 78000/129384 [59:48<1:19:15, 10.80it/s]

[ART] latent var mean=3.4061e+09, min=2.5431e+05
[ART] input std=4.0487e-01, recon std=7.6618e-02

19800: ART 0.3086:  61%|██████    | 79200/129384 [1:00:40<1:16:19, 10.96it/s]

[ART] latent var mean=1.7481e+09, min=1.0860e+04
[ART] input std=4.2652e-01, recon std=5.0456e-02

20100: ART 0.2974:  62%|██████▏   | 80400/129384 [1:01:31<1:12:53, 11.20it/s]

[ART] latent var mean=6.7121e+09, min=6.0170e+04
[ART] input std=4.0575e-01, recon std=9.4984e-02

20400: ART 0.3069:  63%|██████▎   | 81600/129384 [1:02:21<1:12:01, 11.06it/s]

[ART] latent var mean=1.0483e+08, min=7.2673e+04
[ART] input std=4.4790e-01, recon std=3.6010e-02

20700: ART 0.3308:  64%|██████▍   | 82800/129384 [1:03:13<1:12:03, 10.77it/s]

[ART] latent var mean=1.6368e+08, min=8.7395e+03
[ART] input std=4.1265e-01, recon std=3.9938e-02

21000: ART 0.2906:  65%|██████▍   | 84000/129384 [1:04:04<1:09:01, 10.96it/s]

[ART] latent var mean=7.6111e+09, min=4.5126e+04
[ART] input std=3.8728e-01, recon std=6.4726e-02

21300: ART 0.2848:  66%|██████▌   | 85200/129384 [1:04:56<1:07:40, 10.88it/s]

[ART] latent var mean=4.1899e+09, min=4.7305e+04
[ART] input std=3.9497e-01, recon std=8.9955e-02

21600: ART 0.3075:  67%|██████▋   | 86400/129384 [1:05:47<1:03:55, 11.21it/s]

[ART] latent var mean=1.8230e+09, min=8.7636e+04
[ART] input std=4.3377e-01, recon std=5.9911e-02

21900: ART 0.2876:  68%|██████▊   | 87600/129384 [1:06:38<1:03:17, 11.00it/s]

[ART] latent var mean=3.3326e+09, min=3.1551e+04
[ART] input std=3.8924e-01, recon std=7.9681e-02

22200: ART 0.2900:  69%|██████▊   | 88800/129384 [1:07:28<59:56, 11.28it/s]

[ART] latent var mean=9.8364e+09, min=1.9699e+05
[ART] input std=4.1001e-01, recon std=9.1848e-02

22500: ART 0.2779:  70%|██████▉   | 90000/129384 [1:08:18<59:13, 11.08it/s]

[ART] latent var mean=6.5088e+09, min=4.5663e+04
[ART] input std=3.9530e-01, recon std=9.2970e-02

22800: ART 0.2907:  70%|███████   | 91200/129384 [1:09:08<58:32, 10.87it/s]

[ART] latent var mean=8.6102e+08, min=9.4352e+03
[ART] input std=3.8192e-01, recon std=5.7087e-02

23100: ART 0.2839:  71%|███████▏  | 92396/129384 [1:10:00<23:20, 26.42it/s]

[ART] latent var mean=7.5610e+09, min=5.1041e+04
[ART] input std=3.9964e-01, recon std=9.1349e-02

23400: ART 0.2820:  72%|███████▏  | 93596/129384 [1:10:52<24:32, 24.30it/s]

[ART] latent var mean=9.1062e+09, min=8.2330e+04
[ART] input std=3.9216e-01, recon std=8.1226e-02

23700: ART 0.2830:  73%|███████▎  | 94800/129384 [1:11:43<52:42, 10.94it/s]

[ART] latent var mean=5.1089e+09, min=1.6299e+05
[ART] input std=4.3872e-01, recon std=8.4328e-02

24000: ART 0.2876:  74%|███████▍  | 96000/129384 [1:12:35<49:37, 11.21it/s]

[ART] latent var mean=8.2089e+09, min=2.0287e+05
[ART] input std=4.1930e-01, recon std=9.3886e-02

24300: ART 0.2913:  75%|███████▌  | 97200/129384 [1:13:26<48:50, 10.98it/s]

[ART] latent var mean=7.2225e+09, min=5.5543e+04
[ART] input std=4.2416e-01, recon std=8.1821e-02

24600: ART 0.2892:  76%|███████▌  | 98400/129384 [1:14:17<46:02, 11.21it/s]

[ART] latent var mean=7.4782e+09, min=6.2368e+04
[ART] input std=3.7575e-01, recon std=6.9928e-02

24900: ART 0.2913:  77%|███████▋  | 99600/129384 [1:15:09<47:13, 10.51it/s]

[ART] latent var mean=6.6930e+09, min=6.0159e+04
[ART] input std=4.5852e-01, recon std=8.6321e-02

25200: ART 0.2812:  78%|███████▊  | 100800/129384 [1:16:01<42:57, 11.09it/s]

[ART] latent var mean=1.2445e+10, min=3.6418e+04
[ART] input std=4.0257e-01, recon std=8.5105e-02

25500: ART 0.2952:  79%|███████▉  | 102000/129384 [1:16:51<41:05, 11.11it/s]

[ART] latent var mean=8.8867e+09, min=7.9833e+04
[ART] input std=4.4239e-01, recon std=7.7840e-02

25800: ART 0.2785:  80%|███████▉  | 103200/129384 [1:17:45<39:34, 11.03it/s]

[ART] latent var mean=1.0519e+10, min=3.7560e+04
[ART] input std=4.2963e-01, recon std=9.5118e-02

26100: ART 0.3208:  81%|████████  | 104400/129384 [1:18:37<38:08, 10.92it/s]

[ART] latent var mean=3.3985e+07, min=1.2633e+04
[ART] input std=3.8983e-01, recon std=1.3646e-02

26400: ART 0.2769:  82%|████████▏ | 105600/129384 [1:19:29<35:45, 11.09it/s]

[ART] latent var mean=8.0665e+09, min=3.4388e+04
[ART] input std=3.5665e-01, recon std=7.1324e-02

26700: ART 0.3073:  83%|████████▎ | 106800/129384 [1:20:20<33:25, 11.26it/s]

[ART] latent var mean=3.2676e+07, min=1.2209e+04
[ART] input std=3.7351e-01, recon std=7.1437e-03

27000: ART 0.2861:  83%|████████▎ | 108000/129384 [1:21:10<31:59, 11.14it/s]

[ART] latent var mean=1.2041e+10, min=3.0021e+03
[ART] input std=3.8120e-01, recon std=8.6953e-02

27300: ART 0.2804:  84%|████████▍ | 109200/129384 [1:22:01<31:18, 10.75it/s]

[ART] latent var mean=4.9927e+09, min=1.1842e+05
[ART] input std=4.2124e-01, recon std=8.0332e-02

27600: ART 0.2892:  85%|████████▌ | 110400/129384 [1:22:53<30:20, 10.43it/s]

[ART] latent var mean=6.9064e+09, min=1.4929e+04
[ART] input std=4.2446e-01, recon std=7.6025e-02

27900: ART 0.3253:  86%|████████▋ | 111600/129384 [1:23:44<26:39, 11.12it/s]

[ART] latent var mean=9.4280e+09, min=3.9924e+05
[ART] input std=4.4239e-01, recon std=7.4183e-02

28200: ART 0.2763:  87%|████████▋ | 112800/129384 [1:24:35<25:06, 11.01it/s]

[ART] latent var mean=1.3747e+10, min=4.9706e+05
[ART] input std=4.2741e-01, recon std=9.4686e-02

28500: ART 0.2847:  88%|████████▊ | 114000/129384 [1:25:26<24:06, 10.64it/s]

[ART] latent var mean=1.8969e+10, min=1.3439e+05
[ART] input std=4.3528e-01, recon std=8.9123e-02

28800: ART 0.2983:  89%|████████▉ | 115200/129384 [1:26:18<21:18, 11.10it/s]

[ART] latent var mean=1.6823e+10, min=2.0714e+05
[ART] input std=4.2955e-01, recon std=1.0119e-01

29100: ART 0.2762:  90%|████████▉ | 116396/129384 [1:27:08<07:57, 27.19it/s]

[ART] latent var mean=1.1733e+10, min=1.8579e+05
[ART] input std=4.3767e-01, recon std=1.0213e-01

29400: ART 0.2992:  91%|█████████ | 117596/129384 [1:27:59<07:17, 26.94it/s]

[ART] latent var mean=1.2585e+10, min=2.0283e+05
[ART] input std=4.4938e-01, recon std=1.0328e-01

29700: ART 0.3102:  92%|█████████▏| 118796/129384 [1:28:51<06:30, 27.10it/s]

[ART] latent var mean=1.6922e+10, min=1.0977e+05
[ART] input std=4.4237e-01, recon std=7.9812e-02

30000: ART 0.3154:  93%|█████████▎| 119996/129384 [1:29:44<06:00, 26.07it/s]

[ART] latent var mean=1.7728e+10, min=4.1697e+05
[ART] input std=4.0837e-01, recon std=6.6719e-02

30300: ART 0.2892:  94%|█████████▎| 121196/129384 [1:30:35<05:05, 26.84it/s]

[ART] latent var mean=2.0045e+10, min=6.1392e+05
[ART] input std=4.4549e-01, recon std=9.0696e-02

30600: ART 0.2846:  95%|█████████▍| 122396/129384 [1:31:25<04:15, 27.37it/s]

[ART] latent var mean=1.9356e+10, min=2.1910e+04
[ART] input std=3.7347e-01, recon std=6.6055e-02

30900: ART 0.3031:  96%|█████████▌| 123596/129384 [1:32:15<03:32, 27.18it/s]

[ART] latent var mean=1.2349e+10, min=8.3705e+04
[ART] input std=4.6569e-01, recon std=8.9280e-02

31200: ART 0.2997:  96%|█████████▋| 124796/129384 [1:33:05<02:51, 26.79it/s]

[ART] latent var mean=2.6609e+09, min=3.6967e+04
[ART] input std=3.9240e-01, recon std=9.2908e-02

31500: ART 0.2878:  97%|█████████▋| 125996/129384 [1:33:55<02:05, 26.93it/s]

[ART] latent var mean=9.2196e+09, min=2.9990e+03
[ART] input std=4.0763e-01, recon std=6.4284e-02

31800: ART 0.2794:  98%|█████████▊| 127200/129384 [1:34:45<03:14, 11.25it/s]

[ART] latent var mean=2.8608e+10, min=8.3487e+04
[ART] input std=4.0678e-01, recon std=8.9898e-02

32100: ART 0.2871:  99%|█████████▉| 128396/129384 [1:35:35<00:36, 27.03it/s]

[ART] latent var mean=1.7118e+10, min=4.3581e+05
[ART] input std=4.4282e-01, recon std=1.0340e-01

32346: ART 0.2858: 100%|██████████| 129384/129384 [1:36:20<00:00, 22.38it/s]

In [21]:
def temporal_diff(x):
    """
    x: (B, T, ...)
    returns: (B, T-1, ...)
    """
    return x[:, 1:] - x[:, :-1]

def combined_loss(x_hat, x, alpha=0.5):
    """
    alpha: weight on static loss (delta weight = 1-alpha)
    """
    # static loss
    loss_static = F.mse_loss(x_hat, x)

    # delta loss
    dx_hat = temporal_diff(x_hat)
    dx = temporal_diff(x)

    loss_delta = F.mse_loss(dx_hat, dx)

    return alpha * loss_static + (1 - alpha) * loss_delta, loss_static, loss_delta

In [22]:
BATCH_SIZE = 4

In [ ]:
log = {
    "batch_idx": [],
    "loss": [],
}
ac_model = SequenceAutoencoder(
    feature_shape=30,
    latent_dim=1024,
).to(device)

ac_criterion = nn.MSELoss()
ac_optimizer = torch.optim.Adam(ac_model.parameters(), lr=0.001)

shuffled_token_df = token_df.sample(frac=1, random_state=42).reset_index(drop=True)

pbar = tqdm.tqdm(shuffled_token_df.iterrows(), total=len(shuffled_token_df))

ac_model.train()

batch  = []
batch_idx = 0
for idx, (_, data) in enumerate(pbar):

    start, end, phone, art_f, ac_f, subject = data["start"], data["end"], data["phone"], data["art_f"], data["ac_f"], data["subject"]
    
    mfccs = get_mfccs(ac_f, start, end).T

    if mfccs is None:
        continue

    batch.append(
        torch.tensor(mfccs, dtype=torch.float32)
    )

    # --------------------------------------------------
    # When batch is ready
    # --------------------------------------------------
    if len(batch) < BATCH_SIZE:
        continue
    batch_idx += 1
    ac_batch = torch.stack(batch).to(device)  # (B,T,F)
    batch.clear()

    # ===== Acoustic =====
    ac_out, ac_z = ac_model(ac_batch)
    ac_loss, ac_static, ac_delta = combined_loss(
        ac_out, ac_batch
    )

    ac_optimizer.zero_grad()
    ac_loss.backward()
    ac_optimizer.step()

    log["batch_idx"].append(batch_idx)
    log["loss"].append(ac_loss.item())
    pbar.set_description(
        f"{batch_idx}: AC {ac_loss.item():.4f}"
    )

    # --------------------------------------------------
    # Diagnostics every 1000 updates
    # --------------------------------------------------
    if batch_idx % 1000 == 999:
        with torch.no_grad():
            ac_stats  = latent_stats(ac_z)

        print(
            f"[AC ] latent var mean={ac_stats['latent_var_mean']:.4e}, "
            f"min={ac_stats['latent_var_min']:.4e}"
        )
        print(
            f"[AC ] input std={batch_diversity(ac_batch):.4e}, "
            f"recon std={batch_diversity(ac_out):.4e}"
        )

        torch.save(ac_model.state_dict(), "ckpts/aemri/ac_model_ckpt.pth")
        pd.DataFrame(log).to_csv("ckpts/aemri/ac_model_training_log.csv", index=False)

torch.save(ac_model.state_dict(), "ckpts/aemri/ac_model_ckpt.pth")
pd.DataFrame(log).to_csv("ckpts/aemri/ac_model_training_log.csv", index=False)

999: AC 164.7690:   1%|          | 979/129384 [00:05<09:44, 219.67it/s]

[AC ] latent var mean=1.2359e+03, min=8.2164e-04
[AC ] input std=1.4405e+01, recon std=4.0498e+00

1999: AC 126.9526:   2%|▏         | 1996/129384 [00:10<10:01, 211.63it/s]

[AC ] latent var mean=2.9891e+03, min=5.3760e-03
[AC ] input std=1.3895e+01, recon std=5.8752e+00

2999: AC 133.7991:   2%|▏         | 2992/129384 [00:15<09:24, 224.04it/s]

[AC ] latent var mean=3.3248e+02, min=8.8333e-05
[AC ] input std=1.2004e+01, recon std=2.2661e+00

3999: AC 86.0437:   3%|▎         | 3984/129384 [00:20<09:08, 228.43it/s]

[AC ] latent var mean=1.3134e+02, min=2.6905e-04
[AC ] input std=9.7381e+00, recon std=1.2285e+00

5015: AC 195.4979:   4%|▍         | 5007/129384 [00:25<11:59, 172.81it/s]

[AC ] latent var mean=3.7371e+02, min=5.2401e-04
[AC ] input std=9.2020e+00, recon std=2.1808e+00

6015: AC 81.1322:   5%|▍         | 6017/129384 [00:30<13:29, 152.45it/s]

[AC ] latent var mean=7.3926e+02, min=1.6140e-03
[AC ] input std=1.1016e+01, recon std=2.4683e+00

7019: AC 130.1101:   5%|▌         | 7019/129384 [00:35<11:45, 173.41it/s]

[AC ] latent var mean=2.1081e+03, min=3.0256e-03
[AC ] input std=1.3356e+01, recon std=4.2386e+00

8007: AC 113.8775:   6%|▌         | 7992/129384 [00:39<08:53, 227.47it/s]

[AC ] latent var mean=6.5113e+02, min=1.9124e-06
[AC ] input std=1.1422e+01, recon std=2.1420e+00

9003: AC 174.0431:   7%|▋         | 8992/129384 [00:46<13:21, 150.22it/s]

[AC ] latent var mean=5.9069e+03, min=2.4391e-02
[AC ] input std=1.4971e+01, recon std=6.4382e+00

10011: AC 91.7481:   8%|▊         | 10008/129384 [00:52<17:03, 116.61it/s]

[AC ] latent var mean=7.1591e+02, min=3.6688e-03
[AC ] input std=1.3086e+01, recon std=2.6019e+00

11015: AC 111.7888:   9%|▊         | 11003/129384 [00:59<16:55, 116.61it/s]

[AC ] latent var mean=2.8310e+03, min=1.7108e-03
[AC ] input std=1.3488e+01, recon std=6.0296e+00

12011: AC 115.9327:   9%|▉         | 12004/129384 [01:05<16:39, 117.40it/s]

[AC ] latent var mean=8.5750e+03, min=5.9457e-02
[AC ] input std=1.6043e+01, recon std=5.8876e+00

13007: AC 194.0759:  10%|█         | 13008/129384 [01:12<18:03, 107.45it/s]

[AC ] latent var mean=6.4111e+03, min=5.0732e-02
[AC ] input std=1.6404e+01, recon std=7.1688e+00

14011: AC 138.8201:  11%|█         | 14008/129384 [01:19<17:03, 112.70it/s]

[AC ] latent var mean=8.3969e+03, min=1.2791e-03
[AC ] input std=1.7390e+01, recon std=9.5211e+00

15007: AC 146.7039:  12%|█▏        | 15007/129384 [01:25<16:10, 117.80it/s]

[AC ] latent var mean=4.3883e+03, min=3.4930e-03
[AC ] input std=1.3271e+01, recon std=5.7736e+00

16011: AC 216.5135:  12%|█▏        | 16000/129384 [01:32<15:45, 119.92it/s]

[AC ] latent var mean=3.1993e+03, min=6.8302e-03
[AC ] input std=1.5581e+01, recon std=4.2715e+00

17011: AC 115.8229:  13%|█▎        | 17006/129384 [01:39<17:08, 109.28it/s]

[AC ] latent var mean=8.5263e+03, min=2.1430e-02
[AC ] input std=1.3531e+01, recon std=8.0767e+00

18015: AC 127.3580:  14%|█▍        | 18004/129384 [01:46<15:51, 117.07it/s]

[AC ] latent var mean=4.4326e+03, min=4.6542e-03
[AC ] input std=1.5398e+01, recon std=4.7424e+00

19015: AC 144.2522:  15%|█▍        | 19000/129384 [01:52<16:12, 113.49it/s]

[AC ] latent var mean=8.4027e+02, min=2.7379e-03
[AC ] input std=1.0067e+01, recon std=2.7938e+00

20011: AC 116.8441:  15%|█▌        | 20007/129384 [01:59<15:49, 115.23it/s]

[AC ] latent var mean=2.9832e+04, min=1.1350e-01
[AC ] input std=1.7063e+01, recon std=1.1998e+01

21011: AC 105.1216:  16%|█▌        | 21012/129384 [02:06<15:04, 119.88it/s]

[AC ] latent var mean=2.1465e+03, min=7.4798e-03
[AC ] input std=1.1818e+01, recon std=3.1680e+00

22007: AC 122.0767:  17%|█▋        | 22001/129384 [02:13<16:37, 107.64it/s]

[AC ] latent var mean=3.8734e+03, min=1.8051e-02
[AC ] input std=1.3726e+01, recon std=3.7078e+00

23011: AC 285.0106:  18%|█▊        | 23002/129384 [02:19<15:12, 116.54it/s]

[AC ] latent var mean=4.6315e+03, min=2.1254e-02
[AC ] input std=1.3751e+01, recon std=3.3128e+00

24011: AC 227.4720:  19%|█▊        | 24008/129384 [02:26<14:49, 118.47it/s]

[AC ] latent var mean=2.4028e+03, min=2.6716e-03
[AC ] input std=1.2319e+01, recon std=3.4770e+00

25011: AC 108.9203:  19%|█▉        | 25000/129384 [02:32<14:48, 117.48it/s]

[AC ] latent var mean=5.0596e+03, min=4.0744e-02
[AC ] input std=1.1180e+01, recon std=4.2815e+00

26015: AC 95.7119:  20%|██        | 26009/129384 [02:39<14:19, 120.21it/s]

[AC ] latent var mean=5.7259e+03, min=1.6277e-01
[AC ] input std=1.4649e+01, recon std=3.7585e+00

27015: AC 195.3754:  21%|██        | 27005/129384 [02:46<14:10, 120.44it/s]

[AC ] latent var mean=1.0138e+03, min=7.5730e-03
[AC ] input std=1.0547e+01, recon std=2.8168e+00

28015: AC 152.1365:  22%|██▏       | 28002/129384 [02:52<13:58, 120.89it/s]

[AC ] latent var mean=7.1205e+03, min=5.8540e-06
[AC ] input std=1.3853e+01, recon std=3.7966e+00

29011: AC 149.6232:  22%|██▏       | 29013/129384 [02:59<14:03, 119.05it/s]

[AC ] latent var mean=1.5312e+03, min=3.8349e-02
[AC ] input std=9.4438e+00, recon std=2.4445e+00

30007: AC 106.8839:  23%|██▎       | 30007/129384 [03:05<14:48, 111.91it/s]

[AC ] latent var mean=1.3426e+04, min=5.1110e-02
[AC ] input std=1.1442e+01, recon std=4.2066e+00

31015: AC 140.3793:  24%|██▍       | 31007/129384 [03:12<13:00, 126.08it/s]

[AC ] latent var mean=6.4300e+04, min=2.3862e-01
[AC ] input std=1.7448e+01, recon std=9.7439e+00

32015: AC 140.0849:  25%|██▍       | 32000/129384 [03:18<13:33, 119.64it/s]

[AC ] latent var mean=1.4211e+05, min=1.8530e+00
[AC ] input std=1.4688e+01, recon std=6.6203e+00

33003: AC 95.7479:  26%|██▌       | 33000/129384 [03:25<15:29, 103.72it/s]

[AC ] latent var mean=6.8542e+04, min=2.2954e-03
[AC ] input std=1.3789e+01, recon std=5.0403e+00

34015: AC 170.0152:  26%|██▋       | 34001/129384 [03:31<12:23, 128.30it/s]

[AC ] latent var mean=9.7017e+03, min=7.4268e-03
[AC ] input std=1.2356e+01, recon std=3.1941e+00

35011: AC 77.8722:  27%|██▋       | 35012/129384 [03:38<13:14, 118.74it/s]

[AC ] latent var mean=1.1344e+05, min=2.2265e-02
[AC ] input std=1.3984e+01, recon std=5.1543e+00

36015: AC 62.3240:  28%|██▊       | 36008/129384 [03:44<12:52, 120.90it/s]

[AC ] latent var mean=2.3702e+04, min=3.4628e-04
[AC ] input std=1.3118e+01, recon std=4.0570e+00

37011: AC 180.8072:  29%|██▊       | 37012/129384 [03:50<12:56, 119.01it/s]

[AC ] latent var mean=2.9898e+04, min=2.3772e-01
[AC ] input std=1.3329e+01, recon std=3.8083e+00

38015: AC 171.5759:  29%|██▉       | 38000/129384 [03:57<11:55, 127.71it/s]

[AC ] latent var mean=2.5762e+05, min=2.2939e+00
[AC ] input std=1.4091e+01, recon std=6.1711e+00

39015: AC 133.9144:  30%|███       | 39009/129384 [04:03<11:57, 125.95it/s]

[AC ] latent var mean=8.3198e+04, min=1.1998e+01
[AC ] input std=1.6129e+01, recon std=5.7613e+00

40015: AC 123.9221:  31%|███       | 40011/129384 [04:09<11:34, 128.65it/s]

[AC ] latent var mean=5.5966e+04, min=6.9053e-01
[AC ] input std=1.0509e+01, recon std=3.5769e+00

41011: AC 83.3654:  32%|███▏      | 41011/129384 [04:16<12:26, 118.32it/s]

[AC ] latent var mean=1.2256e+05, min=3.4547e-02
[AC ] input std=1.3284e+01, recon std=4.8134e+00

42015: AC 134.1414:  32%|███▏      | 42014/129384 [04:23<11:40, 124.73it/s]

[AC ] latent var mean=9.6363e+03, min=1.3157e-01
[AC ] input std=1.4724e+01, recon std=2.1838e+00

43015: AC 136.8929:  33%|███▎      | 43000/129384 [04:29<12:09, 118.45it/s]

[AC ] latent var mean=5.5296e+04, min=4.2410e-01
[AC ] input std=1.5543e+01, recon std=3.2571e+00

44011: AC 140.3560:  34%|███▍      | 44008/129384 [04:35<11:47, 120.69it/s]

[AC ] latent var mean=3.2410e+05, min=4.1288e-02
[AC ] input std=1.1648e+01, recon std=5.5399e+00

45007: AC 126.2939:  35%|███▍      | 44994/129384 [04:42<08:51, 158.78it/s]

[AC ] latent var mean=3.6354e+05, min=1.2398e+00
[AC ] input std=1.1129e+01, recon std=4.1724e+00

46011: AC 177.2006:  36%|███▌      | 46001/129384 [04:48<11:39, 119.12it/s]

[AC ] latent var mean=1.4128e+06, min=7.4232e+00
[AC ] input std=2.0298e+01, recon std=1.0743e+01

47011: AC 137.5161:  36%|███▋      | 47008/129384 [04:55<11:28, 119.60it/s]

[AC ] latent var mean=1.5906e+05, min=2.5428e+00
[AC ] input std=1.4206e+01, recon std=5.2280e+00

48011: AC 137.4808:  37%|███▋      | 48008/129384 [05:01<11:50, 114.60it/s]

[AC ] latent var mean=6.6230e+04, min=3.7675e+00
[AC ] input std=1.1801e+01, recon std=3.0450e+00

49011: AC 78.7142:  38%|███▊      | 49007/129384 [05:08<11:10, 119.84it/s]

[AC ] latent var mean=7.1576e+04, min=6.7173e-01
[AC ] input std=1.3357e+01, recon std=3.0550e+00

50011: AC 108.0770:  39%|███▊      | 50008/129384 [05:14<11:07, 118.91it/s]

[AC ] latent var mean=1.0723e+06, min=1.3164e+01
[AC ] input std=1.6011e+01, recon std=8.0760e+00

51011: AC 100.0711:  39%|███▉      | 51012/129384 [05:21<10:55, 119.63it/s]

[AC ] latent var mean=5.3247e+04, min=1.0394e-01
[AC ] input std=1.1308e+01, recon std=3.2173e+00

52007: AC 91.9662:  40%|████      | 52003/129384 [05:27<10:44, 120.06it/s]

[AC ] latent var mean=1.1921e+06, min=3.8123e+01
[AC ] input std=1.0764e+01, recon std=4.1699e+00

53015: AC 118.1986:  41%|████      | 53007/129384 [05:34<10:16, 123.98it/s]

[AC ] latent var mean=5.5275e+05, min=1.5003e+01
[AC ] input std=1.3089e+01, recon std=4.2849e+00

54015: AC 126.1822:  42%|████▏     | 54008/129384 [05:40<10:18, 121.86it/s]

[AC ] latent var mean=6.9429e+05, min=6.5604e+00
[AC ] input std=1.1857e+01, recon std=3.8295e+00

55011: AC 130.5612:  43%|████▎     | 55003/129384 [05:46<09:56, 124.77it/s]

[AC ] latent var mean=3.3498e+05, min=4.9689e+00
[AC ] input std=1.1091e+01, recon std=3.8025e+00

56015: AC 85.0539:  43%|████▎     | 56014/129384 [05:53<09:34, 127.62it/s]

[AC ] latent var mean=2.0358e+05, min=1.5034e+01
[AC ] input std=9.6874e+00, recon std=3.4547e+00

57011: AC 100.6428:  44%|████▍     | 57008/129384 [05:59<10:02, 120.19it/s]

[AC ] latent var mean=3.5624e+06, min=1.8226e+02
[AC ] input std=1.2783e+01, recon std=6.9512e+00

58015: AC 133.5924:  45%|████▍     | 58011/129384 [06:06<09:26, 125.90it/s]

[AC ] latent var mean=4.9219e+05, min=2.0046e+01
[AC ] input std=1.2847e+01, recon std=3.6435e+00

59011: AC 112.7051:  46%|████▌     | 59008/129384 [06:12<09:45, 120.13it/s]

[AC ] latent var mean=1.3224e+06, min=4.5525e+01
[AC ] input std=1.2319e+01, recon std=4.1887e+00

60015: AC 132.9986:  46%|████▋     | 60013/129384 [06:18<09:27, 122.26it/s]

[AC ] latent var mean=3.1529e+06, min=4.2293e+01
[AC ] input std=1.4828e+01, recon std=6.9635e+00

61011: AC 108.8864:  47%|████▋     | 61000/129384 [06:25<09:35, 118.92it/s]

[AC ] latent var mean=2.1930e+06, min=5.7466e+00
[AC ] input std=1.2265e+01, recon std=5.7749e+00

62015: AC 99.5875:  48%|████▊     | 62012/129384 [06:31<09:01, 124.40it/s]

[AC ] latent var mean=1.9517e+06, min=3.0903e+01
[AC ] input std=1.3590e+01, recon std=5.0650e+00

63011: AC 146.2425:  49%|████▊     | 63005/129384 [06:38<09:11, 120.39it/s]

[AC ] latent var mean=2.6473e+06, min=3.4839e+01
[AC ] input std=1.4469e+01, recon std=4.8444e+00

64011: AC 170.1591:  49%|████▉     | 64007/129384 [06:44<08:55, 122.17it/s]

[AC ] latent var mean=1.3290e+06, min=7.8319e+00
[AC ] input std=1.0631e+01, recon std=4.2425e+00

65015: AC 116.4175:  50%|█████     | 65008/129384 [06:50<08:54, 120.50it/s]

[AC ] latent var mean=5.3511e+06, min=2.6173e+02
[AC ] input std=1.4734e+01, recon std=6.7665e+00

66011: AC 170.5633:  51%|█████     | 66008/129384 [06:57<09:04, 116.45it/s]

[AC ] latent var mean=9.0628e+06, min=8.3446e+02
[AC ] input std=1.5739e+01, recon std=7.9202e+00

67011: AC 165.0434:  52%|█████▏    | 67008/129384 [07:03<08:55, 116.54it/s]

[AC ] latent var mean=1.5378e+06, min=1.1132e+01
[AC ] input std=1.3065e+01, recon std=3.5498e+00

68015: AC 135.3754:  53%|█████▎    | 68006/129384 [07:10<08:18, 123.12it/s]

[AC ] latent var mean=4.3622e+06, min=1.9227e+01
[AC ] input std=1.0934e+01, recon std=4.8452e+00

69011: AC 97.9108:  53%|█████▎    | 69000/129384 [07:16<08:35, 117.18it/s]

[AC ] latent var mean=6.4804e+05, min=1.5497e+01
[AC ] input std=1.0489e+01, recon std=3.4916e+00

70011: AC 147.9516:  54%|█████▍    | 70012/129384 [07:22<08:07, 121.75it/s]

[AC ] latent var mean=1.2795e+07, min=1.2476e+02
[AC ] input std=1.2119e+01, recon std=7.7870e+00

71011: AC 168.1971:  55%|█████▍    | 71007/129384 [07:29<08:03, 120.69it/s]

[AC ] latent var mean=7.4738e+05, min=1.9454e+01
[AC ] input std=1.3179e+01, recon std=3.2336e+00

72011: AC 181.4132:  56%|█████▌    | 72004/129384 [07:35<08:11, 116.64it/s]

[AC ] latent var mean=1.0556e+07, min=5.6379e+01
[AC ] input std=1.6696e+01, recon std=6.7073e+00

73011: AC 152.1686:  56%|█████▋    | 73012/129384 [07:42<07:54, 118.74it/s]

[AC ] latent var mean=2.6932e+06, min=9.1158e-01
[AC ] input std=1.0895e+01, recon std=3.8965e+00

74011: AC 79.1105:  57%|█████▋    | 74010/129384 [07:48<07:35, 121.66it/s]

[AC ] latent var mean=7.1300e+06, min=8.9077e+01
[AC ] input std=1.4680e+01, recon std=5.0200e+00

75011: AC 88.3182:  58%|█████▊    | 75005/129384 [07:55<07:48, 116.09it/s]

[AC ] latent var mean=2.2545e+06, min=9.3044e-02
[AC ] input std=1.0791e+01, recon std=3.3552e+00

76011: AC 92.8770:  59%|█████▊    | 76009/129384 [08:01<07:31, 118.31it/s]

[AC ] latent var mean=2.9788e+06, min=1.4537e-02
[AC ] input std=1.6094e+01, recon std=4.8160e+00

77011: AC 223.4969:  60%|█████▉    | 77001/129384 [08:07<07:25, 117.63it/s]

[AC ] latent var mean=1.2751e+06, min=8.5582e+00
[AC ] input std=1.4612e+01, recon std=3.2980e+00

78011: AC 219.4160:  60%|██████    | 78004/129384 [08:14<07:19, 116.85it/s]

[AC ] latent var mean=1.2559e+07, min=2.5892e+01
[AC ] input std=1.4404e+01, recon std=4.9959e+00

79011: AC 158.1469:  61%|██████    | 79009/129384 [08:20<07:12, 116.35it/s]

[AC ] latent var mean=2.9428e+06, min=7.7099e+01
[AC ] input std=1.1593e+01, recon std=3.6149e+00

80015: AC 161.9724:  62%|██████▏   | 80014/129384 [08:27<06:37, 124.10it/s]

[AC ] latent var mean=8.0445e+06, min=2.1398e+02
[AC ] input std=1.2341e+01, recon std=3.9785e+00

81011: AC 175.0329:  63%|██████▎   | 81009/129384 [08:33<06:46, 118.97it/s]

[AC ] latent var mean=4.3323e+06, min=1.1624e+02
[AC ] input std=1.2783e+01, recon std=4.1051e+00

82011: AC 148.2776:  63%|██████▎   | 82012/129384 [08:40<06:38, 118.79it/s]

[AC ] latent var mean=3.1909e+06, min=1.2833e-02
[AC ] input std=1.1196e+01, recon std=3.8853e+00

83007: AC 148.7849:  64%|██████▍   | 82996/129384 [08:46<05:00, 154.25it/s]

[AC ] latent var mean=2.4525e+07, min=6.1421e+02
[AC ] input std=1.8580e+01, recon std=5.1769e+00

84011: AC 137.6637:  65%|██████▍   | 84001/129384 [08:53<06:21, 118.99it/s]

[AC ] latent var mean=3.3373e+06, min=1.7313e+01
[AC ] input std=9.4762e+00, recon std=3.8927e+00

85011: AC 184.9601:  66%|██████▌   | 85010/129384 [08:59<06:24, 115.41it/s]

[AC ] latent var mean=4.8428e+06, min=5.0171e+01
[AC ] input std=1.4854e+01, recon std=3.9347e+00

86015: AC 84.3761:  66%|██████▋   | 86004/129384 [09:06<06:06, 118.26it/s]

[AC ] latent var mean=7.0383e+07, min=8.4942e+01
[AC ] input std=1.7647e+01, recon std=7.7681e+00

87011: AC 78.2661:  67%|██████▋   | 87008/129384 [09:12<05:58, 118.23it/s]

[AC ] latent var mean=1.0902e+07, min=1.5592e+02
[AC ] input std=1.4438e+01, recon std=4.5776e+00

88011: AC 91.6091:  68%|██████▊   | 88012/129384 [09:19<05:44, 119.93it/s]

[AC ] latent var mean=2.7868e+07, min=7.5265e+02
[AC ] input std=1.5472e+01, recon std=5.6367e+00

89011: AC 101.4048:  69%|██████▉   | 89012/129384 [09:25<05:48, 115.88it/s]

[AC ] latent var mean=8.2076e+06, min=9.1048e+01
[AC ] input std=1.1416e+01, recon std=4.6820e+00

90007: AC 105.8832:  70%|██████▉   | 90002/129384 [09:32<05:38, 116.34it/s]

[AC ] latent var mean=1.3587e+06, min=1.1738e+01
[AC ] input std=1.3230e+01, recon std=3.4584e+00

91011: AC 138.6021:  70%|███████   | 91008/129384 [09:38<05:25, 117.76it/s]

[AC ] latent var mean=4.6171e+07, min=1.9106e+02
[AC ] input std=1.5973e+01, recon std=8.2287e+00

92011: AC 107.7418:  71%|███████   | 92000/129384 [09:45<05:20, 116.48it/s]

[AC ] latent var mean=8.3545e+06, min=6.0276e+02
[AC ] input std=1.2844e+01, recon std=4.3037e+00

93011: AC 149.6747:  72%|███████▏  | 93011/129384 [09:51<05:01, 120.64it/s]

[AC ] latent var mean=2.3171e+07, min=4.5670e+02
[AC ] input std=1.3994e+01, recon std=3.9728e+00

94011: AC 167.1323:  73%|███████▎  | 94008/129384 [09:58<05:02, 116.82it/s]

[AC ] latent var mean=8.1103e+07, min=1.8212e+02
[AC ] input std=1.2341e+01, recon std=7.2353e+00

95011: AC 98.3109:  73%|███████▎  | 95009/129384 [10:04<04:51, 117.90it/s]

[AC ] latent var mean=9.0913e+06, min=3.0089e+01
[AC ] input std=1.3170e+01, recon std=4.2601e+00

96011: AC 99.4662:  74%|███████▍  | 96012/129384 [10:11<04:45, 116.72it/s]

[AC ] latent var mean=9.2288e+07, min=5.1010e+02
[AC ] input std=1.6593e+01, recon std=8.3469e+00

97011: AC 169.9065:  75%|███████▍  | 97000/129384 [10:17<04:40, 115.54it/s]

[AC ] latent var mean=9.5492e+07, min=1.9877e+03
[AC ] input std=1.3769e+01, recon std=7.1335e+00

98011: AC 204.2998:  76%|███████▌  | 98004/129384 [10:24<04:31, 115.43it/s]

[AC ] latent var mean=1.7130e+07, min=8.7850e+02
[AC ] input std=1.2193e+01, recon std=4.5134e+00

99011: AC 137.2114:  77%|███████▋  | 99004/129384 [10:30<04:24, 114.75it/s]

[AC ] latent var mean=7.9672e+06, min=6.4446e+02
[AC ] input std=1.0186e+01, recon std=3.4172e+00

100011: AC 120.0429:  77%|███████▋  | 100012/129384 [10:37<04:09, 117.70it/s]

[AC ] latent var mean=7.3631e+06, min=7.1932e+02
[AC ] input std=1.2153e+01, recon std=3.3392e+00

101011: AC 199.4730:  78%|███████▊  | 100999/129384 [10:43<02:53, 163.64it/s]

[AC ] latent var mean=1.4423e+06, min=1.4887e+02
[AC ] input std=1.3951e+01, recon std=3.3003e+00

102011: AC 139.6741:  79%|███████▉  | 102010/129384 [10:50<03:57, 115.42it/s]

[AC ] latent var mean=2.7102e+07, min=1.2946e+03
[AC ] input std=1.1465e+01, recon std=5.1158e+00

103007: AC 105.2769:  80%|███████▉  | 103000/129384 [10:56<03:59, 110.17it/s]

[AC ] latent var mean=4.2683e+07, min=8.8547e+02
[AC ] input std=1.4292e+01, recon std=6.0792e+00

103999: AC 214.5213:  80%|████████  | 103992/129384 [11:03<02:44, 154.46it/s]

[AC ] latent var mean=5.4362e+07, min=9.3458e+01
[AC ] input std=1.5196e+01, recon std=4.8123e+00

104999: AC 237.3135:  81%|████████  | 104980/129384 [11:08<01:51, 219.00it/s]

[AC ] latent var mean=1.4195e+08, min=5.5843e+01
[AC ] input std=1.7334e+01, recon std=7.7351e+00

105999: AC 117.5108:  82%|████████▏ | 105987/129384 [11:13<01:47, 216.82it/s]

[AC ] latent var mean=1.8144e+07, min=1.3954e+01
[AC ] input std=1.4126e+01, recon std=4.3997e+00

106999: AC 453.1873:  83%|████████▎ | 106980/129384 [11:18<01:43, 216.22it/s]

[AC ] latent var mean=1.5085e+08, min=1.1674e+04
[AC ] input std=2.1002e+01, recon std=8.6553e+00

107999: AC 117.9933:  83%|████████▎ | 107984/129384 [11:23<01:40, 213.94it/s]

[AC ] latent var mean=2.0021e+07, min=9.8151e+02
[AC ] input std=1.0717e+01, recon std=3.6427e+00

108999: AC 114.0280:  84%|████████▍ | 108986/129384 [11:28<01:36, 212.19it/s]

[AC ] latent var mean=1.1175e+08, min=5.6836e+03
[AC ] input std=1.4792e+01, recon std=7.1768e+00

109999: AC 93.8617:  85%|████████▌ | 109984/129384 [11:33<01:29, 216.13it/s]

[AC ] latent var mean=7.5020e+07, min=1.5285e+04
[AC ] input std=1.1891e+01, recon std=6.0066e+00

110999: AC 99.3893:  86%|████████▌ | 110980/129384 [11:38<01:25, 216.18it/s]

[AC ] latent var mean=4.0472e+07, min=3.8883e+03
[AC ] input std=1.1584e+01, recon std=4.6305e+00

111999: AC 145.8646:  87%|████████▋ | 111986/129384 [11:43<01:20, 217.38it/s]

[AC ] latent var mean=8.2801e+07, min=2.6227e+03
[AC ] input std=1.3554e+01, recon std=7.1504e+00

112999: AC 150.9263:  87%|████████▋ | 112996/129384 [11:48<01:16, 215.01it/s]

[AC ] latent var mean=8.0579e+07, min=1.7292e+03
[AC ] input std=1.3913e+01, recon std=6.2403e+00

113999: AC 85.4376:  88%|████████▊ | 113976/129384 [11:53<01:09, 220.68it/s]

[AC ] latent var mean=2.2970e+07, min=8.7451e+00
[AC ] input std=1.1611e+01, recon std=4.4834e+00

114999: AC 73.9233:  89%|████████▉ | 114992/129384 [11:58<01:04, 221.70it/s]

[AC ] latent var mean=1.2220e+07, min=5.3055e+01
[AC ] input std=1.0343e+01, recon std=3.5549e+00

115999: AC 150.5083:  90%|████████▉ | 115984/129384 [12:03<01:00, 219.95it/s]

[AC ] latent var mean=1.7047e+08, min=1.9154e+02
[AC ] input std=1.7419e+01, recon std=7.2757e+00

116999: AC 76.9010:  90%|█████████ | 116988/129384 [12:07<00:58, 212.68it/s]

[AC ] latent var mean=3.2950e+07, min=2.8121e+02
[AC ] input std=1.0586e+01, recon std=5.6128e+00

117999: AC 90.4618:  91%|█████████ | 117976/129384 [12:12<00:56, 201.99it/s]

[AC ] latent var mean=5.7912e+07, min=4.0086e+00
[AC ] input std=1.2094e+01, recon std=5.8231e+00

118999: AC 106.2341:  92%|█████████▏| 118984/129384 [12:17<00:47, 216.70it/s]

[AC ] latent var mean=4.9844e+07, min=1.1451e+01
[AC ] input std=1.2384e+01, recon std=6.2328e+00

119999: AC 86.2269:  93%|█████████▎| 119980/129384 [12:22<00:42, 223.63it/s]

[AC ] latent var mean=1.0115e+07, min=1.9813e+01
[AC ] input std=1.1328e+01, recon std=3.8975e+00

120999: AC 101.6146:  94%|█████████▎| 120995/129384 [12:27<00:38, 220.23it/s]

[AC ] latent var mean=7.6575e+06, min=3.7050e+01
[AC ] input std=1.1338e+01, recon std=3.6515e+00

121999: AC 120.9446:  94%|█████████▍| 121980/129384 [12:32<00:34, 213.41it/s]

[AC ] latent var mean=8.6818e+07, min=8.1928e+01
[AC ] input std=1.4834e+01, recon std=6.1885e+00

122999: AC 73.0465:  95%|█████████▌| 122992/129384 [12:37<00:29, 217.31it/s]

[AC ] latent var mean=2.5335e+08, min=6.9353e+02
[AC ] input std=1.2401e+01, recon std=8.0249e+00

123999: AC 99.5435:  96%|█████████▌| 123996/129384 [12:42<00:24, 220.97it/s]

[AC ] latent var mean=1.5808e+07, min=8.9339e+01
[AC ] input std=1.2233e+01, recon std=3.1004e+00

124999: AC 136.2643:  97%|█████████▋| 124984/129384 [12:47<00:20, 219.36it/s]

[AC ] latent var mean=3.6755e+07, min=2.2890e+02
[AC ] input std=1.3362e+01, recon std=3.7407e+00

125999: AC 118.3695:  97%|█████████▋| 125976/129384 [12:51<00:15, 222.98it/s]

[AC ] latent var mean=4.6797e+07, min=7.2900e+02
[AC ] input std=1.1395e+01, recon std=4.5555e+00

126999: AC 114.0968:  98%|█████████▊| 126996/129384 [12:56<00:10, 224.41it/s]

[AC ] latent var mean=2.8106e+08, min=6.2553e+03
[AC ] input std=1.7060e+01, recon std=8.7386e+00

127999: AC 93.8624:  99%|█████████▉| 127992/129384 [13:01<00:06, 221.48it/s]

[AC ] latent var mean=1.1368e+08, min=2.1283e+02
[AC ] input std=1.2323e+01, recon std=5.8093e+00

128999: AC 92.3924: 100%|█████████▉| 128984/129384 [13:06<00:01, 226.72it/s]

[AC ] latent var mean=7.8645e+07, min=3.9850e+03
[AC ] input std=1.4480e+01, recon std=6.2095e+00

129383: AC 80.4298: 100%|██████████| 129384/129384 [13:08<00:00, 164.13it/s]