In [1]:
import pandas as pd
import tqdm, os
import pickle
import warnings
warnings.simplefilter("ignore")

import sys
sys.path.insert(0, "../..")

from utils.acoustics_processing import get_mfccs
from utils.articulation_processing import get_frmri_articulatory_features

In [2]:
df = pd.read_csv("../data_processing/dataset_construction/datasets/processed_frmri.csv")
df["subject"] = df["art_f"].apply(lambda x: os.path.basename(x).split("_")[1])

In [3]:
df

,phone1_start,phone1_end,phone2_start,phone2_end,phone1,phone2,context,word,word_id,art_f,ac_f,subject
0,2.647,2.717,2.717,2.907,f,i,f,filou,2,/Volumes/Transcend/FR-MRI/P6/OTHER/S1/VIDEO_P6...,/Volumes/Transcend/FR-MRI/P6/OTHER/S1/DENOISED...,P6
1,2.717,2.907,2.907,2.937,i,l,f_i,filou,2,/Volumes/Transcend/FR-MRI/P6/OTHER/S1/VIDEO_P6...,/Volumes/Transcend/FR-MRI/P6/OTHER/S1/DENOISED...,P6
2,2.907,2.937,2.937,3.067,l,u,f_i_l,filou,2,/Volumes/Transcend/FR-MRI/P6/OTHER/S1/VIDEO_P6...,/Volumes/Transcend/FR-MRI/P6/OTHER/S1/DENOISED...,P6
3,3.097,3.157,3.157,3.237,l,a,l,la,4,/Volumes/Transcend/FR-MRI/P6/OTHER/S1/VIDEO_P6...,/Volumes/Transcend/FR-MRI/P6/OTHER/S1/DENOISED...,P6
4,3.237,3.317,3.317,3.377,f,ʁ,f,fripouille,5,/Volumes/Transcend/FR-MRI/P6/OTHER/S1/VIDEO_P6...,/Volumes/Transcend/FR-MRI/P6/OTHER/S1/DENOISED...,P6
...,...,...,...,...,...,...,...,...,...,...,...,...
22432,33.071,33.131,33.131,33.211,ʁ,e,p_ʁ,précises,78,/Volumes/Transcend/FR-MRI/P4/OTHER/S12/VIDEO_P...,/Volumes/Transcend/FR-MRI/P4/OTHER/S12/DENOISE...,P4
22433,33.131,33.211,33.211,33.391,e,s,p_ʁ_e,précises,78,/Volumes/Transcend/FR-MRI/P4/OTHER/S12/VIDEO_P...,/Volumes/Transcend/FR-MRI/P4/OTHER/S12/DENOISE...,P4
22434,33.211,33.391,33.391,33.671,s,i,p_ʁ_e_s,précises,78,/Volumes/Transcend/FR-MRI/P4/OTHER/S12/VIDEO_P...,/Volumes/Transcend/FR-MRI/P4/OTHER/S12/DENOISE...,P4
22435,33.391,33.671,33.671,33.801,i,z,p_ʁ_e_s_i,précises,78,/Volumes/Transcend/FR-MRI/P4/OTHER/S12/VIDEO_P...,/Volumes/Transcend/FR-MRI/P4/OTHER/S12/DENOISE...,P4
22436,33.671,33.801,33.801,33.891,z,ə,p_ʁ_e_s_i_z,précises,78,/Volumes/Transcend/FR-MRI/P4/OTHER/S12/VIDEO_P...,/Volumes/Transcend/FR-MRI/P4/OTHER/S12/DENOISE...,P4

In [ ]:
tokens = {
    "start": [],
    "end": [],
    "syllable": [],
    "art_f": [],
    "ac_f": [],
    "subject": [],
}

metadata = set(
    [(start, end, target, art_f, ac_f, subject) for start, end, target, art_f, ac_f, subject in zip(df["syllable1_start"], df["syllable1_end"], df["syllable1"], df["art_f"], df["ac_f"], df["subject"])] + 
    [(start, end, target, art_f, ac_f, subject) for start, end, target, art_f, ac_f, subject in zip(df["syllable2_start"], df["syllable2_end"], df["syllable2"], df["art_f"], df["ac_f"], df["subject"])]
)

metadata = sorted(list(metadata), key=lambda x: (x[3], x[4], x[5]))

for start, end, target, art_f, ac_f, subject in metadata:
    tokens["start"].append(start)
    tokens["end"].append(end)
    tokens["syllable"].append(target)
    tokens["art_f"].append(art_f)
    tokens["ac_f"].append(ac_f)
    tokens["subject"].append(subject)

In [5]:
token_df = pd.DataFrame(tokens)

In [6]:
token_df

,start,end,phone,art_f,ac_f,subject
0,17.177,17.247,d,/Volumes/Transcend/FR-MRI/P7/OTHER/S6/VIDEO_P7...,/Volumes/Transcend/FR-MRI/P7/OTHER/S6/DENOISED...,P7
1,20.618,20.668,ɛ,/Volumes/Transcend/FR-MRI/P9/OTHER/S11/VIDEO_P...,/Volumes/Transcend/FR-MRI/P9/OTHER/S11/DENOISE...,P9
2,31.072,31.132,ɛ,/Volumes/Transcend/FR-MRI/P10/OTHER/S8/VIDEO_P...,/Volumes/Transcend/FR-MRI/P10/OTHER/S8/DENOISE...,P10
3,23.886,24.066,ʁ,/Volumes/Transcend/FR-MRI/P3/OTHER/S14/VIDEO_P...,/Volumes/Transcend/FR-MRI/P3/OTHER/S14/DENOISE...,P3
4,29.121,29.211,o,/Volumes/Transcend/FR-MRI/P2/OTHER/S6/VIDEO_P2...,/Volumes/Transcend/FR-MRI/P2/OTHER/S6/DENOISED...,P2
...,...,...,...,...,...,...
30593,34.890,35.020,d,/Volumes/Transcend/FR-MRI/P8/OTHER/S2/VIDEO_P8...,/Volumes/Transcend/FR-MRI/P8/OTHER/S2/DENOISED...,P8
30594,24.349,24.429,a,/Volumes/Transcend/FR-MRI/P8/OTHER/S4/VIDEO_P8...,/Volumes/Transcend/FR-MRI/P8/OTHER/S4/DENOISED...,P8
30595,17.719,17.789,a,/Volumes/Transcend/FR-MRI/P8/OTHER/S6/VIDEO_P8...,/Volumes/Transcend/FR-MRI/P8/OTHER/S6/DENOISED...,P8
30596,31.439,31.539,e,/Volumes/Transcend/FR-MRI/P8/OTHER/S8/VIDEO_P8...,/Volumes/Transcend/FR-MRI/P8/OTHER/S8/DENOISED...,P8
30597,5.731,5.811,p,/Volumes/Transcend/FR-MRI/P10/OTHER/S8/VIDEO_P...,/Volumes/Transcend/FR-MRI/P10/OTHER/S8/DENOISE...,P10

In [7]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from utils.models import VideoAutoencoder, SequenceAutoencoder

In [8]:
def latent_stats(z):
    # z: (B, latent_dim)
    return {
        "latent_var_mean": z.var(dim=0).mean().item(),
        "latent_var_min":  z.var(dim=0).min().item(),
        "latent_var_max":  z.var(dim=0).max().item(),
    }

def batch_diversity(x):
    # x: (B, ...)
    x_flat = x.reshape(x.size(0), -1)
    return x_flat.std(dim=0).mean().item()

def visualize(clean, recon, name="Reconstruction"):
    import matplotlib.pyplot as plt

    try:
        # Get both channels, frame 0 of first batch element
        clean_mri= clean[0, 0, 0].cpu().numpy()
    except RuntimeError:
        clean_mri = clean[0, 0, 0].detach().cpu().numpy()

    recon_mri = recon[0, 0, 0].detach().cpu().numpy()

    plt.figure(figsize=(10, 6))

    plt.subplot(1, 2, 1)
    plt.imshow(clean_mri, cmap='gray')
    plt.title("Original (MRI)")
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(recon_mri, cmap='gray')
    plt.title(f"{name} (MRI)")
    plt.axis('off')

    plt.tight_layout()
    plt.savefig(f"video_visualization/frmri/{name.lower()}.png", dpi=300)
    plt.close("all")

def combined_loss(y_true, y_pred, warped_x, criterion, plot=False, ratio=1):
    diff_true = y_true[:, :, 1:, :, :] - y_true[:, :, :-1, :, :]
    diff_pred = y_pred[:, :, 1:, :, :] - y_pred[:, :, :-1, :, :]
    loss = criterion(diff_true, diff_pred) * (1 - ratio) + criterion(y_true, y_pred) * ratio

    if plot:
        visualize(diff_true, diff_pred, name="Reconstruction (differential)")
        visualize(y_true, y_pred, name="Reconstruction")
        visualize(y_true, warped_x, name="Transformation")

    return loss

In [9]:
device = "mps" if torch.backends.mps.is_available() else "cpu"

BATCH_SIZE = 4

In [14]:
log = {
    "batch_idx": [],
    "loss": [],
}

art_model = VideoAutoencoder(
    input_shape=(5, 136, 136),
    latent_dim=1024,
    use_mlp=True,
    grid_sample_cpu_fallback=True,
).to(device)

art_criterion = nn.MSELoss()
art_optimizer = torch.optim.Adam(art_model.parameters(), lr=0.001)

shuffled_token_df = token_df.sample(frac=1, random_state=42).reset_index(drop=True)

pbar = tqdm.tqdm(shuffled_token_df.iterrows(), total=len(shuffled_token_df))

art_model.train()

batch = []
batch_idx = 0
for idx, (_, data) in enumerate(pbar):

    start, end, phone, art_f, ac_f, subject = data["start"], data["end"], data["phone"], data["art_f"], data["ac_f"], data["subject"]
    
    articulatory_features = get_frmri_articulatory_features(art_f, start, end)
    if articulatory_features.shape[-2:]!=(136, 136):
        continue
    if articulatory_features is None:
        continue

    batch.append(
        torch.tensor(articulatory_features, dtype=torch.float32)
    )

    # --------------------------------------------------
    # When batch is ready
    # --------------------------------------------------
    if len(batch) < BATCH_SIZE:
        continue
    batch_idx += 1
    try:
        art_batch = torch.stack(batch).to(device)  # (B,T,P,C)
    except RuntimeError:
        continue
    batch.clear()

    # ===== Articulatory =====
    art_out, art_warped_x, art_z = art_model(art_batch, return_warped_x=True, return_latent=True)
    art_loss = combined_loss(art_batch, art_out, art_warped_x, art_criterion, plot=batch_idx % 30 == 0, ratio=0.5)

    art_optimizer.zero_grad()
    art_loss.backward()
    art_optimizer.step()

    log["batch_idx"].append(batch_idx)
    log["loss"].append(art_loss.item())
    pbar.set_description(
        f"{batch_idx}: ART {art_loss.item():.4f}"
    )

    # --------------------------------------------------
    # Diagnostics every 1000 updates
    # --------------------------------------------------
    if (batch_idx) % 300 == 0:
        with torch.no_grad():
            art_stats = latent_stats(art_z)

        print(
            f"[ART] latent var mean={art_stats['latent_var_mean']:.4e}, "
            f"min={art_stats['latent_var_min']:.4e}"
        )

        print(
            f"[ART] input std={batch_diversity(art_batch):.4e}, "
            f"recon std={batch_diversity(art_out):.4e}"
        )

        torch.save(art_model.state_dict(), "ckpts/frmri/art_model_ckpt.pth")
        pd.DataFrame(log).to_csv("ckpts/frmri/art_model_training_log.csv", index=False)

torch.save(art_model.state_dict(), "ckpts/frmri/art_model_ckpt.pth")
pd.DataFrame(log).to_csv("ckpts/frmri/art_model_training_log.csv", index=False)

300: ART 0.3355:   4%|▍         | 1200/30598 [02:28<57:20,  8.54it/s]

[ART] latent var mean=8.2897e+04, min=7.3986e-03
[ART] input std=3.7416e-01, recon std=8.8942e-02

600: ART 0.3500:   8%|▊         | 2409/30598 [05:36<1:38:24,  4.77it/s]

[ART] latent var mean=1.0582e+05, min=9.9631e-01
[ART] input std=4.7592e-01, recon std=4.1980e-02

900: ART 0.3386:  12%|█▏        | 3611/30598 [08:49<56:12,  8.00it/s]

[ART] latent var mean=2.6182e+06, min=2.7111e+00
[ART] input std=5.1331e-01, recon std=1.3581e-01

1200: ART 0.3406:  16%|█▌        | 4815/30598 [11:25<53:55,  7.97it/s]

[ART] latent var mean=3.8261e+06, min=7.5844e+00
[ART] input std=5.8051e-01, recon std=1.1749e-01

1500: ART 0.3480:  20%|█▉        | 6017/30598 [13:56<49:56,  8.20it/s]

[ART] latent var mean=6.0719e+05, min=5.8069e+00
[ART] input std=4.5254e-01, recon std=3.9291e-02

1800: ART 0.3511:  24%|██▎       | 7222/30598 [16:28<47:24,  8.22it/s]

[ART] latent var mean=1.3232e+06, min=5.1498e-01
[ART] input std=4.8455e-01, recon std=6.1868e-02

2100: ART 0.3338:  28%|██▊       | 8428/30598 [19:00<45:28,  8.12it/s]

[ART] latent var mean=6.9760e+06, min=6.1713e+00
[ART] input std=4.3159e-01, recon std=1.1482e-01

2400: ART 0.3338:  31%|███▏      | 9630/30598 [21:31<41:37,  8.39it/s]

[ART] latent var mean=5.6398e+06, min=3.2266e+00
[ART] input std=5.1656e-01, recon std=8.5595e-02

2700: ART 0.3266:  35%|███▌      | 10832/30598 [24:02<39:04,  8.43it/s]

[ART] latent var mean=2.3929e+07, min=3.8688e+01
[ART] input std=5.2752e-01, recon std=1.3287e-01

3000: ART 0.3320:  39%|███▉      | 12037/30598 [26:33<37:04,  8.34it/s]

[ART] latent var mean=4.5234e+07, min=2.8909e+02
[ART] input std=5.0969e-01, recon std=1.2117e-01

3300: ART 0.3114:  43%|████▎     | 13239/30598 [29:03<35:59,  8.04it/s]

[ART] latent var mean=4.8702e+07, min=3.8329e+01
[ART] input std=5.4424e-01, recon std=1.5436e-01

3600: ART 0.3154:  47%|████▋     | 14444/30598 [31:35<31:57,  8.42it/s]

[ART] latent var mean=7.3347e+07, min=4.4837e+02
[ART] input std=5.5361e-01, recon std=1.6310e-01

3900: ART 0.3686:  51%|█████     | 15650/30598 [34:06<30:05,  8.28it/s]

[ART] latent var mean=1.6521e+07, min=6.8492e+00
[ART] input std=3.1931e-01, recon std=1.0013e-01

4200: ART 0.3516:  55%|█████▌    | 16857/30598 [36:38<27:58,  8.19it/s]

[ART] latent var mean=3.6025e+07, min=1.6713e+01
[ART] input std=4.5545e-01, recon std=1.4700e-01

4500: ART 0.3201:  59%|█████▉    | 18059/30598 [39:08<25:13,  8.28it/s]

[ART] latent var mean=2.0881e+07, min=2.8245e+01
[ART] input std=4.6189e-01, recon std=1.1526e-01

4800: ART 0.3127:  63%|██████▎   | 19267/30598 [41:39<22:57,  8.23it/s]

[ART] latent var mean=4.2092e+07, min=1.3809e+02
[ART] input std=4.6192e-01, recon std=1.3856e-01

5100: ART 0.3378:  67%|██████▋   | 20473/30598 [44:10<20:05,  8.40it/s]

[ART] latent var mean=2.1221e+08, min=1.6730e+01
[ART] input std=4.7263e-01, recon std=9.9027e-02

5400: ART 0.3158:  71%|███████   | 21677/30598 [46:42<17:53,  8.31it/s]

[ART] latent var mean=5.1512e+07, min=2.4616e+02
[ART] input std=4.6957e-01, recon std=1.0131e-01

5700: ART 0.3667:  75%|███████▍  | 22879/30598 [49:12<15:20,  8.39it/s]

[ART] latent var mean=2.1374e+08, min=5.2779e+02
[ART] input std=4.5077e-01, recon std=1.6030e-01

6000: ART 0.3426:  79%|███████▊  | 24083/30598 [51:56<13:23,  8.11it/s]

[ART] latent var mean=7.2368e+06, min=2.0331e+00
[ART] input std=4.4259e-01, recon std=4.1993e-02

6300: ART 0.3174:  83%|████████▎ | 25287/30598 [54:34<11:31,  7.68it/s]

[ART] latent var mean=1.9459e+08, min=5.8718e+01
[ART] input std=5.0139e-01, recon std=1.3814e-01

6600: ART 0.3335:  87%|████████▋ | 26489/30598 [57:11<08:31,  8.03it/s]

[ART] latent var mean=2.8360e+08, min=7.1346e+02
[ART] input std=5.3180e-01, recon std=1.4843e-01

6900: ART 0.3270:  91%|█████████ | 27694/30598 [1:00:01<06:56,  6.97it/s]

[ART] latent var mean=3.6351e+08, min=1.7557e+02
[ART] input std=4.8827e-01, recon std=1.5050e-01

7200: ART 0.3347:  94%|█████████▍| 28899/30598 [1:02:48<03:30,  8.06it/s]

[ART] latent var mean=3.8783e+08, min=1.3280e+02
[ART] input std=5.2553e-01, recon std=1.5963e-01

7500: ART 0.3295:  98%|█████████▊| 30102/30598 [1:05:25<01:02,  7.93it/s]

[ART] latent var mean=2.7761e+08, min=7.4498e+00
[ART] input std=3.6293e-01, recon std=9.7558e-02

7622: ART 0.3287: 100%|██████████| 30598/30598 [1:06:29<00:00,  7.67it/s]

In [12]:
def temporal_diff(x):
    """
    x: (B, T, ...)
    returns: (B, T-1, ...)
    """
    return x[:, 1:] - x[:, :-1]

def combined_loss(x_hat, x, alpha=0.5):
    """
    alpha: weight on static loss (delta weight = 1-alpha)
    """
    # static loss
    loss_static = F.mse_loss(x_hat, x)

    # delta loss
    dx_hat = temporal_diff(x_hat)
    dx = temporal_diff(x)

    loss_delta = F.mse_loss(dx_hat, dx)

    return alpha * loss_static + (1 - alpha) * loss_delta, loss_static, loss_delta

In [13]:
BATCH_SIZE = 4

In [ ]:
log = {
    "batch_idx": [],
    "loss": [],
}
ac_model = SequenceAutoencoder(
    feature_shape=30,
    latent_dim=1024,
).to(device)

ac_criterion = nn.MSELoss()
ac_optimizer = torch.optim.Adam(ac_model.parameters(), lr=0.001)

shuffled_token_df = token_df.sample(frac=1, random_state=42).reset_index(drop=True)

pbar = tqdm.tqdm(shuffled_token_df.iterrows(), total=len(shuffled_token_df))

ac_model.train()

batch  = []
batch_idx = 0
for idx, (_, data) in enumerate(pbar):

    start, end, phone, art_f, ac_f, subject = data["start"], data["end"], data["phone"], data["art_f"], data["ac_f"], data["subject"]
    
    mfccs = get_mfccs(ac_f, start, end).T

    if mfccs is None:
        continue

    batch.append(
        torch.tensor(mfccs, dtype=torch.float32)
    )

    # --------------------------------------------------
    # When batch is ready
    # --------------------------------------------------
    if len(batch) < BATCH_SIZE:
        continue
    batch_idx += 1

    ac_batch = torch.stack(batch).to(device)  # (B,T,F)
    batch.clear()

    # ===== Acoustic =====
    ac_out, ac_z = ac_model(ac_batch)
    ac_loss, ac_static, ac_delta = combined_loss(
        ac_out, ac_batch
    )

    ac_optimizer.zero_grad()
    ac_loss.backward()
    ac_optimizer.step()

    log["batch_idx"].append(batch_idx)
    log["loss"].append(ac_loss.item())
    pbar.set_description(
        f"{batch_idx}: AC {ac_loss.item():.4f}"
    )

    # --------------------------------------------------
    # Diagnostics every 1000 updates
    # --------------------------------------------------
    if batch_idx % 1000 == 999:
        with torch.no_grad():
            ac_stats  = latent_stats(ac_z)

        print(
            f"[AC ] latent var mean={ac_stats['latent_var_mean']:.4e}, "
            f"min={ac_stats['latent_var_min']:.4e}"
        )
        print(
            f"[AC ] input std={batch_diversity(ac_batch):.4e}, "
            f"recon std={batch_diversity(ac_out):.4e}"
        )

        torch.save(ac_model.state_dict(), "ckpts/frmri/ac_model_ckpt.pth")
        pd.DataFrame(log).to_csv("ckpts/frmri/ac_model_training_log.csv", index=False)

torch.save(ac_model.state_dict(), "ckpts/frmri/ac_model_ckpt.pth")
pd.DataFrame(log).to_csv("ckpts/frmri/ac_model_training_log.csv", index=False)

999: AC 396.5454:   3%|▎         | 996/30598 [00:08<02:31, 195.93it/s]

[AC ] latent var mean=1.0226e+04, min=3.6491e-01
[AC ] input std=1.8567e+01, recon std=5.9596e+00

1999: AC 277.8782:   7%|▋         | 1993/30598 [00:13<02:31, 189.37it/s]

[AC ] latent var mean=7.8073e+03, min=3.4647e-01
[AC ] input std=1.6948e+01, recon std=6.1636e+00

2999: AC 368.7260:  10%|▉         | 2989/30598 [00:19<02:21, 194.83it/s]

[AC ] latent var mean=9.2809e+03, min=3.9698e-01
[AC ] input std=1.9983e+01, recon std=5.4185e+00

3999: AC 277.8535:  13%|█▎        | 3983/30598 [00:24<02:11, 202.12it/s]

[AC ] latent var mean=1.4145e+03, min=5.5894e-02
[AC ] input std=1.4626e+01, recon std=2.4188e+00

5019: AC 262.7433:  16%|█▋        | 5009/30598 [00:30<02:45, 154.49it/s]

[AC ] latent var mean=5.7300e+04, min=1.1921e+00
[AC ] input std=2.0586e+01, recon std=8.4337e+00

6015: AC 375.6702:  20%|█▉        | 6012/30598 [00:35<03:34, 114.39it/s]

[AC ] latent var mean=9.4802e+03, min=8.6882e-02
[AC ] input std=1.6395e+01, recon std=5.3060e+00

7003: AC 279.0180:  23%|██▎       | 7003/30598 [00:42<03:51, 101.81it/s]

[AC ] latent var mean=8.3842e+03, min=9.4094e-02
[AC ] input std=1.9601e+01, recon std=5.2635e+00

7999: AC 184.3381:  26%|██▌       | 7991/30598 [00:47<01:49, 206.44it/s]

[AC ] latent var mean=2.1165e+03, min=7.5244e-04
[AC ] input std=1.1933e+01, recon std=3.3932e+00

9007: AC 310.4046:  29%|██▉       | 9000/30598 [00:52<02:30, 143.32it/s]

[AC ] latent var mean=3.0648e+04, min=5.1826e-01
[AC ] input std=2.2323e+01, recon std=8.2881e+00

10011: AC 367.5918:  33%|███▎      | 9999/30598 [00:57<01:40, 205.44it/s]

[AC ] latent var mean=3.1682e+04, min=6.6174e-02
[AC ] input std=1.9626e+01, recon std=8.2864e+00

11015: AC 328.8713:  36%|███▌      | 11004/30598 [01:03<02:07, 153.65it/s]

[AC ] latent var mean=3.0268e+04, min=9.4688e-02
[AC ] input std=1.9552e+01, recon std=8.6385e+00

12015: AC 162.5531:  39%|███▉      | 12008/30598 [01:08<02:09, 143.44it/s]

[AC ] latent var mean=1.9862e+04, min=2.3447e-01
[AC ] input std=1.6714e+01, recon std=7.5247e+00

13015: AC 417.3814:  43%|████▎     | 13007/30598 [01:15<02:31, 115.96it/s]

[AC ] latent var mean=1.3085e+04, min=1.6829e-01
[AC ] input std=1.5121e+01, recon std=6.9593e+00

14015: AC 218.4070:  46%|████▌     | 14011/30598 [01:22<02:18, 119.35it/s]

[AC ] latent var mean=1.0106e+04, min=1.2196e-03
[AC ] input std=1.8402e+01, recon std=5.7069e+00

15015: AC 162.3521:  49%|████▉     | 15000/30598 [01:29<02:17, 113.84it/s]

[AC ] latent var mean=4.3826e+04, min=1.2082e-02
[AC ] input std=1.9207e+01, recon std=9.3487e+00

16011: AC 291.2180:  52%|█████▏    | 16003/30598 [01:36<02:05, 116.72it/s]

[AC ] latent var mean=7.8778e+03, min=7.6993e-04
[AC ] input std=1.9063e+01, recon std=5.3919e+00

17011: AC 426.0009:  56%|█████▌    | 17003/30598 [01:43<01:58, 114.34it/s]

[AC ] latent var mean=5.8286e+03, min=8.9595e-02
[AC ] input std=2.1668e+01, recon std=4.3465e+00

18015: AC 253.2543:  59%|█████▉    | 18003/30598 [01:50<01:51, 112.63it/s]

[AC ] latent var mean=1.1128e+04, min=2.3350e-03
[AC ] input std=1.6407e+01, recon std=4.9331e+00

19011: AC 189.1058:  62%|██████▏   | 19007/30598 [01:57<01:39, 116.67it/s]

[AC ] latent var mean=3.1257e+04, min=1.2829e-01
[AC ] input std=1.8662e+01, recon std=6.8189e+00

20015: AC 671.2585:  65%|██████▌   | 20000/30598 [02:04<01:34, 112.43it/s]

[AC ] latent var mean=7.8046e+04, min=5.1643e-01
[AC ] input std=1.7945e+01, recon std=8.3003e+00

21011: AC 399.1334:  69%|██████▊   | 21007/30598 [02:11<01:22, 115.60it/s]

[AC ] latent var mean=1.2913e+04, min=1.3765e-03
[AC ] input std=1.7015e+01, recon std=5.6838e+00

22011: AC 344.8421:  72%|███████▏  | 22003/30598 [02:18<01:12, 117.92it/s]

[AC ] latent var mean=1.2461e+03, min=2.0527e-03
[AC ] input std=1.4349e+01, recon std=2.4210e+00

23011: AC 170.4561:  75%|███████▌  | 23007/30598 [02:25<01:05, 116.07it/s]

[AC ] latent var mean=2.9886e+03, min=5.1995e-03
[AC ] input std=1.5121e+01, recon std=3.4045e+00

24015: AC 351.9766:  78%|███████▊  | 24000/30598 [02:32<00:59, 111.69it/s]

[AC ] latent var mean=7.6401e+04, min=1.1058e+00
[AC ] input std=1.8434e+01, recon std=8.6821e+00

25011: AC 529.4619:  82%|████████▏ | 25012/30598 [02:38<00:48, 115.24it/s]

[AC ] latent var mean=2.3078e+03, min=2.0496e-04
[AC ] input std=1.1707e+01, recon std=2.7166e+00

25999: AC 199.3528:  85%|████████▍ | 25991/30598 [02:45<00:30, 150.78it/s]

[AC ] latent var mean=9.3246e+04, min=4.7248e-01
[AC ] input std=2.3344e+01, recon std=9.3126e+00

26999: AC 286.7572:  88%|████████▊ | 26985/30598 [02:50<00:17, 207.50it/s]

[AC ] latent var mean=1.0492e+04, min=4.5163e-02
[AC ] input std=1.4553e+01, recon std=4.9615e+00

28007: AC 221.5164:  92%|█████████▏| 28010/30598 [02:56<00:18, 138.14it/s]

[AC ] latent var mean=5.1813e+05, min=1.4107e+00
[AC ] input std=1.3909e+01, recon std=5.7342e+00

29019: AC 183.3245:  95%|█████████▍| 29006/30598 [03:01<00:10, 158.95it/s]

[AC ] latent var mean=1.1618e+05, min=5.7804e-02
[AC ] input std=1.3536e+01, recon std=4.2334e+00

30015: AC 128.6266:  98%|█████████▊| 30012/30598 [03:06<00:03, 152.12it/s]

[AC ] latent var mean=8.7271e+05, min=4.5761e+01
[AC ] input std=2.1250e+01, recon std=6.3229e+00

30595: AC 327.0703: 100%|██████████| 30598/30598 [03:10<00:00, 160.80it/s]